# Generated by Django 4.2.10 on 2024-03-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
    ]
